#!/usr/bin/python
#  coding=utf-8

if __name__ == '__main__':
    import os
    import sys
    import logging
    import settings

    base_path = os.path.dirname(os.path.realpath(__file__))
    sys.path.append(base_path)

    from feedbacknotifier.src.lib import logger
    from feedbacknotifier.src import Notifier

    logger_path = "/var/log/feedback-notifier" if settings.FEEDBACK_NOTIFIER_GLOBAL_LOG else os.path.join(base_path, settings.LOG_PATH)

    logger.init_logger(logging.NOTSET, logger_path)

    notifier = Notifier(base_path)
    notifier.run()
